version: '3.9'

services:
    authservice:
      container_name: "thirumathikart_authservice"
      image: "thirumathikart_authservice"
      build:
        context: .
        target: ${TARGET}
      ports: 
        - ${SERVER_PORT}:${SERVER_PORT}
      volumes:
        - .:/app  

    authdb:
      privileged: true
      container_name: "thirumathikart_authdb"
      image: postgres
      restart: always
      env_file:
        - .env
      volumes:
        - ./pg_db:/data/postgres:rw

    authadminer:
      container_name: "adminer_authdb"
      image: adminer
      restart: always
      ports:
        - ${ADMINER_PORT}:8080

networks:
  default:
      external:
        name: thirumathikart_network
